# Generated by Django 4.2.7 on 2026-04-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
