# Generated by Django 5.2.13 on 2026-04-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_alter_items_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='new_added_item',
            field=models.BooleanField(default=False, help_text='Check to show in New Arrivals'),
        ),
    ]
