# Generated by Django 5.2.13 on 2026-04-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_alter_items_new_added_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_image',
            field=models.ImageField(default='https://stock.adobe.com/search?k=food+logo', upload_to=''),
        ),
    ]
