# Generated by Django 5.2.13 on 2026-04-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_alter_items_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_image',
            field=models.URLField(default='https://stock.adobe.com/search?k=food+logo'),
        ),
    ]
