# Generated by Django 5.2.13 on 2026-04-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_alter_items_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_image',
            field=models.URLField(default='https://t3.ftcdn.net/jpg/08/29/90/88/360_F_829908823_kYsRKdQcIaYEAhHRAZTIXuSKvuVPif8w.jpg'),
        ),
    ]
